config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :code, presence: true
  validates :name, presence: true
  validates :vol, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @items = Item.new
  end

  def create
    @items = Item.new(item_params)
    if @items.save
      redirect_to root_path, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def show
    @items = Item.all
  end

  def edit
    @items = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
  end

  def destroy
    item = Item.find(params[:id])
    if item.destroy
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def item_params
    params.require(:item).permit(
    :code, 
    :name,
    :vol,
  ) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
%ul
  - @items.errors.full_messages.each do |message|
    %li= message
= form_for @items do |f|
  商品コード
  = f.text_field :code, placeholder: '数字で入力してください'
  %br/
  商品名
  = f.text_field :name, placeholder: '商品名を入力してください'
  %br/
  数量
  = f.text_field :vol, placeholder: '数字で入力してください'
  %br/
  = f.submit

app/views/items/_header.html.haml
.header
  =link_to root_path do
    .headerUpper__link
      =image_tag "/logo.png", alt:"Itemove icon",id: "public", class: "image"

app/views/items/_item.html.haml
.content
  - @items.each do |item|
    %div
      %p= item.code
      %p= item.name
      %p
        = item.vol
        ロット

app/views/items/edit.html.haml
%header
  = render "header"
  = render partial: 'form'

app/views/items/index.html.haml
%body
  %header
    =render "header"
    = link_to 'アイテム登録', new_item_path
    %br/
    現在登録されているアイテム一覧
    - @items.each do | item |
      .item
        = link_to '削除', "/items/#{item.id}", method: :delete
        = link_to '編集', "/items/#{item.id}/edit", method: :get
        .item-code
          商品コード  #{item.code}
        .item-name
          商品名  #{item.name}
        .item-vol
          数量  #{item.vol}
        .item_created_at
          初回登録  #{item.created_at}
        .item_updated_at
          最終更新  #{item.updated_at}

app/views/items/new.html.haml
%header
  = render "header"
  = render partial: 'form'

app/views/items/update.html.haml
更新しました。
%a.btn{:href => "/"} トップへ

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Itemove2
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield